image:
  file: Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306 # Expose the MySQL port
    onOpen: ignore
checkoutLocation: "lamp"
workspaceLocation: "."
tasks:
  - name: MySQL
    command: >
        mysqld --initialize-insecure; # no root password is generated
        mysqld &
        sleep 5;
        cd $GITPOD_REPO_ROOT;
  - name: Apache
    command: >
        apachectl start;
  - name: Lamp
    command: >
        chmod 660 $GITPOD_REPO_ROOT/.htaccess;
        cd $GITPOD_REPO_ROOT;
